//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ABB.Robotics.ScreenMaker.Windows.Forms;
using System;


namespace ScreenGroepsOpdracht
{
    
    
    public class MainScreen : ABB.Robotics.ScreenMaker.Windows.Forms.ScreenForm
    {
        
        private ABB.Robotics.Tps.Windows.Forms.Button button1;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button2;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button3;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel1;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel2;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel3;
        
        private ABB.Robotics.Tps.Windows.Forms.BarGraph barGraph1;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led1;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel4;
        
        public MainScreen()
        {
            this.InitializeComponent();
        }
        
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            this.button1 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button2 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button3 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.tpsLabel1 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel2 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel3 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.barGraph1 = new ABB.Robotics.Tps.Windows.Forms.BarGraph();
            this.tpsLabel4 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.led1 = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.SuspendLayout();
            // 
            // button1
            // 
            this.button1.BackColor = System.Drawing.Color.White;
            this.button1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.button1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button1.Location = new System.Drawing.Point(32, 76);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(140, 70);
            this.button1.Text = "Klik hier";
            this.button1.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button1.Click += new System.EventHandler(this.button1_Click);
            // 
            // button2
            // 
            this.button2.BackColor = System.Drawing.Color.White;
            this.button2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.button2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button2.Location = new System.Drawing.Point(32, 186);
            this.button2.Name = "button2";
            this.button2.Size = new System.Drawing.Size(140, 70);
            this.button2.Text = "Klik hier";
            this.button2.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button2.Click += new System.EventHandler(this.button2_Click);
            // 
            // button3
            // 
            this.button3.BackColor = System.Drawing.Color.White;
            this.button3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.button3.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button3.Location = new System.Drawing.Point(32, 298);
            this.button3.Name = "button3";
            this.button3.Size = new System.Drawing.Size(140, 70);
            this.button3.Text = "Klik hier";
            this.button3.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button3.Click += new System.EventHandler(this.button3_Click);
            // 
            // tpsLabel1
            // 
            this.tpsLabel1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.tpsLabel1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel1.Location = new System.Drawing.Point(32, 46);
            this.tpsLabel1.Multiline = true;
            this.tpsLabel1.Name = "tpsLabel1";
            this.tpsLabel1.Size = new System.Drawing.Size(100, 24);
            this.tpsLabel1.Title = "Start";
            // 
            // tpsLabel2
            // 
            this.tpsLabel2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.tpsLabel2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel2.Location = new System.Drawing.Point(32, 156);
            this.tpsLabel2.Multiline = true;
            this.tpsLabel2.Name = "tpsLabel2";
            this.tpsLabel2.Size = new System.Drawing.Size(100, 24);
            this.tpsLabel2.Title = "Stop";
            // 
            // tpsLabel3
            // 
            this.tpsLabel3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.tpsLabel3.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel3.Location = new System.Drawing.Point(32, 268);
            this.tpsLabel3.Multiline = true;
            this.tpsLabel3.Name = "tpsLabel3";
            this.tpsLabel3.Size = new System.Drawing.Size(100, 24);
            this.tpsLabel3.Title = "Reset";
            // 
            // barGraph1
            // 
            this.barGraph1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.barGraph1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.barGraph1.Location = new System.Drawing.Point(211, 76);
            this.barGraph1.Name = "barGraph1";
            this.barGraph1.Orientation = System.Windows.Forms.Orientation.Horizontal;
            this.barGraph1.Size = new System.Drawing.Size(150, 50);
            // 
            // tpsLabel4
            // 
            this.tpsLabel4.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.tpsLabel4.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel4.Location = new System.Drawing.Point(238, 46);
            this.tpsLabel4.Multiline = true;
            this.tpsLabel4.Name = "tpsLabel4";
            this.tpsLabel4.Size = new System.Drawing.Size(100, 24);
            this.tpsLabel4.Title = "Progress";
            // 
            // led1
            // 
            this.led1.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.RapidDataObject("T_ROB1", "MainModule", "sockErrorConFlag")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.led1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led1.Location = new System.Drawing.Point(415, 46);
            this.led1.Name = "led1";
            this.led1.Size = new System.Drawing.Size(221, 36);
            this.led1.Text = "ERR_SOCK_TIMEOUT";
            // 
            // MainScreen
            // 
            this.BackColor = System.Drawing.SystemColors.Control;
            this.Controls.Add(this.led1);
            this.Controls.Add(this.tpsLabel4);
            this.Controls.Add(this.barGraph1);
            this.Controls.Add(this.tpsLabel3);
            this.Controls.Add(this.tpsLabel2);
            this.Controls.Add(this.tpsLabel1);
            this.Controls.Add(this.button3);
            this.Controls.Add(this.button2);
            this.Controls.Add(this.button1);
            this.Controls.SetChildIndex(this.button1, 0);
            this.Controls.SetChildIndex(this.button2, 0);
            this.Controls.SetChildIndex(this.button3, 0);
            this.Controls.SetChildIndex(this.tpsLabel1, 0);
            this.Controls.SetChildIndex(this.tpsLabel2, 0);
            this.Controls.SetChildIndex(this.tpsLabel3, 0);
            this.Controls.SetChildIndex(this.barGraph1, 0);
            this.Controls.SetChildIndex(this.tpsLabel4, 0);
            this.Controls.SetChildIndex(this.led1, 0);
            this.ResumeLayout(false);
        }
        #endregion
        
        private void button1_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling RapidDataWrite
                ABB.Robotics.ScreenMaker.Base.IApplicationVariable write_0 = this.ScreenServices.ApplicationVariables["stateStart"];
                ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetRapidData(this, "RAPID/T_ROB1/MainModule/state").Value = ((ABB.Robotics.Controllers.RapidDomain.IRapidData)(write_0.Value));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button1_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button2_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling SignalSet
                ((ABB.Robotics.Controllers.IOSystemDomain.DigitalSignal)(ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetSignal(this, "IOSYSTEM/SIGNALS/stopDO"))).Set();
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button2_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button3_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling SignalSet
                ((ABB.Robotics.Controllers.IOSystemDomain.DigitalSignal)(ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetSignal(this, "IOSYSTEM/SIGNALS/resetDO"))).Set();
                // Calling RapidDataWrite
                ABB.Robotics.ScreenMaker.Base.IApplicationVariable write_1 = this.ScreenServices.ApplicationVariables["stateReset"];
                ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetRapidData(this, "RAPID/T_ROB1/MainModule/state").Value = ((ABB.Robotics.Controllers.RapidDomain.IRapidData)(write_1.Value));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button3_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
    }
}
