<Project>
	<PropertyGroup>
		<MainScreenIndex>0</MainScreenIndex>
	</PropertyGroup>
	<ScreenMakerVersion>23.3</ScreenMakerVersion>
	<Type>FlexPendant</Type>
	<References />
	<Controller GUID="b820f0af-3021-400d-a54d-a43a15df350d" Name="LAPTOP-IMJ4O2FE" System="IRB120_3_58" />
	<AssemblyInfo>
		<Title></Title>
		<Description>Code generated by ScreenMaker - Internal version 23.3.10550.0</Description>
		<Company></Company>
		<Product></Product>
		<Copyright></Copyright>
		<Trademark></Trademark>
		<Version>6.13.4007</Version>
	</AssemblyInfo>
	<TpsViewInfo>
		<Caption>ScreenGroepsOpdracht App</Caption>
		<MenuImageName>tpu-Operator32.png</MenuImageName>
		<TaskbarImageName>tpu-Operator32.png</TaskbarImageName>
		<StartPanelLocation>1</StartPanelLocation>
		<ViewType>1</ViewType>
		<StartupType>0</StartupType>
	</TpsViewInfo>
	<ApplicationVariables>
		<Variable Name="stateStart" Value="&quot;Start&quot;" ValueType="ABB.Robotics.Controllers.RapidDomain.String,ABB.Robotics.Controllers.PC" />
		<Variable Name="stateReset" Value="&quot;Reset&quot;" ValueType="ABB.Robotics.Controllers.RapidDomain.String,ABB.Robotics.Controllers.PC" />
		<Variable Name="stateStop" Value="&quot;Stop&quot;" ValueType="ABB.Robotics.Controllers.RapidDomain.String,ABB.Robotics.Controllers.PC" />
	</ApplicationVariables>
	<ItemGroup />
	<ItemGroup>
		<Compile Include=".\MainScreen.view">
			<Link>MainScreen.view</Link>
		</Compile>
	</ItemGroup>
	<StartVirtualFlexPendant>False</StartVirtualFlexPendant>
	<FPSDKInfo>
		<Version>6.13.4007</Version>
	</FPSDKInfo>
	<WidgetInfo />
</Project>