//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

[assembly: System.Reflection.AssemblyTitleAttribute("")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("Code generated by ScreenMaker - Internal version 23.3.10550.0")]
[assembly: System.Reflection.AssemblyCompanyAttribute("")]
[assembly: System.Reflection.AssemblyProductAttribute("")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("")]
[assembly: System.Reflection.AssemblyTrademarkAttribute("")]
[assembly: System.Reflection.AssemblyCultureAttribute("")]
[assembly: System.Reflection.AssemblyVersionAttribute("6.13.4007")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("23.4.10609.1")]
[assembly: ABB.Robotics.Tps.Taf.TpsViewAttribute("ScreenGroepsOpdracht App", "tpu-Operator32.png", "tpu-Operator32.png", "TpsViewScreenGroepsOpdracht.dll", "ScreenGroepsOpdracht.MainScreen", ABB.Robotics.Tps.Taf.StartPanelLocation.Left, ABB.Robotics.Tps.Taf.TpsViewType.Static, ABB.Robotics.Tps.Taf.TpsViewStartupTypes.Manual)]


