//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ABB.Robotics.ScreenMaker.Windows.Forms;
using System;


namespace HuiswerkScreenMaker
{
    
    
    public class MainScreen : ABB.Robotics.ScreenMaker.Windows.Forms.ScreenForm
    {
        
        private ABB.Robotics.Tps.Windows.Forms.Button Home;
        
        private ABB.Robotics.Tps.Windows.Forms.Button ToggleScherm;
        
        private ABB.Robotics.Tps.Windows.Forms.Button Target;
        
        public MainScreen()
        {
            this.InitializeComponent();
        }
        
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            this.Home = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.ToggleScherm = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.Target = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.SuspendLayout();
            // 
            // Home
            // 
            this.Home.BackColor = System.Drawing.Color.White;
            this.Home.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.Home.ForeColor = System.Drawing.SystemColors.ControlText;
            this.Home.Location = new System.Drawing.Point(94, 136);
            this.Home.Name = "Home";
            this.Home.Size = new System.Drawing.Size(140, 70);
            this.Home.Text = "Home";
            this.Home.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.Home.Click += new System.EventHandler(this.Home_Click);
            // 
            // ToggleScherm
            // 
            this.ToggleScherm.BackColor = System.Drawing.Color.White;
            this.ToggleScherm.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.ToggleScherm.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ToggleScherm.Location = new System.Drawing.Point(239, 285);
            this.ToggleScherm.Name = "ToggleScherm";
            this.ToggleScherm.Size = new System.Drawing.Size(140, 70);
            this.ToggleScherm.Text = "Switch Moven";
            this.ToggleScherm.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            // 
            // Target
            // 
            this.Target.BackColor = System.Drawing.Color.White;
            this.Target.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.Target.ForeColor = System.Drawing.SystemColors.ControlText;
            this.Target.Location = new System.Drawing.Point(382, 136);
            this.Target.Name = "Target";
            this.Target.Size = new System.Drawing.Size(140, 70);
            this.Target.Text = "Target";
            this.Target.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            // 
            // MainScreen
            // 
            this.BackColor = System.Drawing.SystemColors.Control;
            this.Controls.Add(this.Target);
            this.Controls.Add(this.ToggleScherm);
            this.Controls.Add(this.Home);
            this.Controls.SetChildIndex(this.Home, 0);
            this.Controls.SetChildIndex(this.ToggleScherm, 0);
            this.Controls.SetChildIndex(this.Target, 0);
            this.ResumeLayout(false);
        }
        #endregion
        
        private void Home_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling RapidDataWrite
                ABB.Robotics.ScreenMaker.Base.IApplicationVariable write_0 = this.ScreenServices.ApplicationVariables["moveHome"];
                ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetRapidData(this, "RAPID/T_ROB1/MainModule/screenInput").Value = ((ABB.Robotics.Controllers.RapidDomain.IRapidData)(write_0.Value));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in Home_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        #region Protected Methods
        protected override void OnInstall(ABB.Robotics.ScreenMaker.Base.IScreenServices services)
        {
            if ((services.ApplicationVariables.Count == 0))
            {
                // 
                // moveHome
                // 
                ABB.Robotics.ScreenMaker.Base.ApplicationVariable moveHome = new ABB.Robotics.ScreenMaker.Base.ApplicationVariable("moveHome", "\"MoveHome\"", typeof(ABB.Robotics.Controllers.RapidDomain.String));
                // 
                // Store variables
                // 
                services.ApplicationVariables.Add("moveHome", moveHome);
            }
            base.OnInstall(services);
        }
        #endregion
    }
}
