//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ABB.Robotics.ScreenMaker.Windows.Forms;
using System;


namespace HuiswerkScreenMaker
{
    
    
    public class MoveHomeScherm : ABB.Robotics.ScreenMaker.Windows.Forms.ScreenForm
    {
        
        private ABB.Robotics.Tps.Windows.Forms.Button Home;
        
        private ABB.Robotics.Tps.Windows.Forms.BarGraph barGraph1;
        
        private ABB.Robotics.Tps.Windows.Forms.Button ResetTeller;
        
        private ABB.Robotics.Tps.Windows.Forms.Button ToggleScherm;
        
        public MoveHomeScherm()
        {
            this.InitializeComponent();
        }
        
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            this.Home = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.ToggleScherm = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.barGraph1 = new ABB.Robotics.Tps.Windows.Forms.BarGraph();
            this.ResetTeller = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.SuspendLayout();
            // 
            // Home
            // 
            this.Home.BackColor = System.Drawing.Color.White;
            this.Home.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.Home.ForeColor = System.Drawing.SystemColors.ControlText;
            this.Home.Location = new System.Drawing.Point(250, 150);
            this.Home.Name = "Home";
            this.Home.Size = new System.Drawing.Size(140, 70);
            this.Home.Text = "Home";
            this.Home.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.Home.Click += new System.EventHandler(this.Home_Click);
            // 
            // ToggleScherm
            // 
            this.ToggleScherm.BackColor = System.Drawing.Color.White;
            this.ToggleScherm.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.ToggleScherm.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ToggleScherm.Location = new System.Drawing.Point(250, 285);
            this.ToggleScherm.Name = "ToggleScherm";
            this.ToggleScherm.Size = new System.Drawing.Size(140, 70);
            this.ToggleScherm.Text = "Toggle Scherm";
            this.ToggleScherm.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.ToggleScherm.Click += new System.EventHandler(this.ToggleScherm_Click);
            // 
            // barGraph1
            // 
            this.barGraph1.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.RapidDataObject("T_ROB1", "MainModule", "tellerMoveHome")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.barGraph1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.barGraph1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.barGraph1.Location = new System.Drawing.Point(539, 70);
            this.barGraph1.Maximum = new decimal(new int[] {
                        256,
                        0,
                        0,
                        0});
            this.barGraph1.Name = "barGraph1";
            this.barGraph1.Size = new System.Drawing.Size(20, 150);
            this.barGraph1.Value = new decimal(new int[] {
                        0,
                        0,
                        0,
                        0});
            this.barGraph1.ValuePlacement = ABB.Robotics.Tps.Windows.Forms.BarValuePlacement.Bottom;
            // 
            // ResetTeller
            // 
            this.ResetTeller.BackColor = System.Drawing.Color.White;
            this.ResetTeller.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.ResetTeller.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ResetTeller.Location = new System.Drawing.Point(479, 285);
            this.ResetTeller.Name = "ResetTeller";
            this.ResetTeller.Size = new System.Drawing.Size(140, 70);
            this.ResetTeller.Text = "Reset Teller";
            this.ResetTeller.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.ResetTeller.Click += new System.EventHandler(this.ResetTeller_Click);
            // 
            // MoveHomeScherm
            // 
            this.BackColor = System.Drawing.SystemColors.Control;
            this.Controls.Add(this.ResetTeller);
            this.Controls.Add(this.barGraph1);
            this.Controls.Add(this.ToggleScherm);
            this.Controls.Add(this.Home);
            this.Controls.SetChildIndex(this.Home, 0);
            this.Controls.SetChildIndex(this.ToggleScherm, 0);
            this.Controls.SetChildIndex(this.barGraph1, 0);
            this.Controls.SetChildIndex(this.ResetTeller, 0);
            this.ResumeLayout(false);
        }
        #endregion
        
        private void Home_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling RapidDataWrite
                ABB.Robotics.ScreenMaker.Base.IApplicationVariable write_0 = this.ScreenServices.ApplicationVariables["moveHome"];
                ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetRapidData(this, "RAPID/T_ROB1/MainModule/screenInput").Value = ((ABB.Robotics.Controllers.RapidDomain.IRapidData)(write_0.Value));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in Home_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void ToggleScherm_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(MoveTargetScherm));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in ToggleScherm_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void ResetTeller_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling RapidDataWrite
                ABB.Robotics.ScreenMaker.Base.IApplicationVariable write_0 = this.ScreenServices.ApplicationVariables["buttonTeller"];
                ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetRapidData(this, "RAPID/T_ROB1/MainModule/resetInput").Value = ((ABB.Robotics.Controllers.RapidDomain.IRapidData)(write_0.Value));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in ResetTeller_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        #region Protected Methods
        protected override void OnInstall(ABB.Robotics.ScreenMaker.Base.IScreenServices services)
        {
            if ((services.ApplicationVariables.Count == 0))
            {
                // 
                // moveHome
                // 
                ABB.Robotics.ScreenMaker.Base.ApplicationVariable moveHome = new ABB.Robotics.ScreenMaker.Base.ApplicationVariable("moveHome", "\"MoveHome\"", typeof(ABB.Robotics.Controllers.RapidDomain.String));
                // 
                // moveTarget
                // 
                ABB.Robotics.ScreenMaker.Base.ApplicationVariable moveTarget = new ABB.Robotics.ScreenMaker.Base.ApplicationVariable("moveTarget", "\"MoveTarget\"", typeof(ABB.Robotics.Controllers.RapidDomain.String));
                // 
                // buttonTeller
                // 
                ABB.Robotics.ScreenMaker.Base.ApplicationVariable buttonTeller = new ABB.Robotics.ScreenMaker.Base.ApplicationVariable("buttonTeller", "1", typeof(ABB.Robotics.Controllers.RapidDomain.Num));
                // 
                // Store variables
                // 
                services.ApplicationVariables.Add("moveHome", moveHome);
                services.ApplicationVariables.Add("moveTarget", moveTarget);
                services.ApplicationVariables.Add("buttonTeller", buttonTeller);
            }
            base.OnInstall(services);
        }
        #endregion
    }
}
