<Project>
	<PropertyGroup>
		<MainScreenIndex>0</MainScreenIndex>
	</PropertyGroup>
	<ScreenMakerVersion>23.3</ScreenMakerVersion>
	<Type>FlexPendant</Type>
	<References />
	<Controller GUID="586f8585-7ab3-4f31-8daf-222980ba22c7" Name="LAPTOP-IMJ4O2FE" System="IRB120FGL_3_58" />
	<AssemblyInfo>
		<Title></Title>
		<Description>Code generated by ScreenMaker - Internal version 23.3.10550.0</Description>
		<Company></Company>
		<Product></Product>
		<Copyright></Copyright>
		<Trademark></Trademark>
		<Version>6.13.4007</Version>
	</AssemblyInfo>
	<TpsViewInfo>
		<Caption>HuiswerkScreenMaker App</Caption>
		<MenuImageName>tpu-Operator32.png</MenuImageName>
		<TaskbarImageName>tpu-Operator32.png</TaskbarImageName>
		<StartPanelLocation>1</StartPanelLocation>
		<ViewType>1</ViewType>
		<StartupType>0</StartupType>
	</TpsViewInfo>
	<ApplicationVariables>
		<Variable Name="moveHome" Value="&quot;MoveHome&quot;" ValueType="ABB.Robotics.Controllers.RapidDomain.String,ABB.Robotics.Controllers.PC" />
		<Variable Name="moveTarget" Value="&quot;MoveTarget&quot;" ValueType="ABB.Robotics.Controllers.RapidDomain.String,ABB.Robotics.Controllers.PC" />
		<Variable Name="buttonTeller" Value="1" ValueType="ABB.Robotics.Controllers.RapidDomain.Num,ABB.Robotics.Controllers.PC" />
	</ApplicationVariables>
	<ItemGroup />
	<ItemGroup>
		<Compile Include=".\MoveHomeScherm.view">
			<Link>MoveHomeScherm.view</Link>
		</Compile>
		<Compile Include=".\MoveTargetScherm.view">
			<Link>MoveTargetScherm.view</Link>
		</Compile>
	</ItemGroup>
	<StartVirtualFlexPendant>False</StartVirtualFlexPendant>
	<FPSDKInfo>
		<Version>6.13.4007</Version>
	</FPSDKInfo>
	<WidgetInfo />
</Project>