//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ABB.Robotics.ScreenMaker.Windows.Forms;
using System;


namespace SocketTest
{
    
    
    public class MainScreen : ABB.Robotics.ScreenMaker.Windows.Forms.ScreenForm
    {
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel1;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led1;
        
        private ABB.Robotics.Tps.Windows.Forms.DataEditor dataEditor1;
        
        public MainScreen()
        {
            this.InitializeComponent();
        }
        
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            this.tpsLabel1 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.dataEditor1 = new ABB.Robotics.Tps.Windows.Forms.DataEditor();
            this.led1 = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.SuspendLayout();
            // 
            // tpsLabel1
            // 
            this.tpsLabel1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.tpsLabel1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel1.Location = new System.Drawing.Point(246, 220);
            this.tpsLabel1.Multiline = true;
            this.tpsLabel1.Name = "tpsLabel1";
            this.tpsLabel1.Size = new System.Drawing.Size(100, 24);
            this.tpsLabel1.Title = "Kleur lamp";
            // 
            // dataEditor1
            // 
            this.dataEditor1.DataBindings.Add(new System.Windows.Forms.Binding("Text", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.RapidDataObject("T_ROB1", "MainModule", "inputVenster")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.dataEditor1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.dataEditor1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.dataEditor1.Location = new System.Drawing.Point(246, 250);
            this.dataEditor1.Name = "dataEditor1";
            this.dataEditor1.Size = new System.Drawing.Size(186, 40);
            this.dataEditor1.Text = "Vul hier een kleur in";
            // 
            // led1
            // 
            this.led1.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.RapidDataObject("T_ROB1", "MainModule", "sockErrorConFlag")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.led1.ForeColor = System.Drawing.Color.Red;
            this.led1.Location = new System.Drawing.Point(12, 67);
            this.led1.Name = "led1";
            this.led1.Size = new System.Drawing.Size(216, 36);
            this.led1.Text = "ERR_SCK_TIMEOUT";
            // 
            // MainScreen
            // 
            this.BackColor = System.Drawing.SystemColors.Control;
            this.Controls.Add(this.led1);
            this.Controls.Add(this.dataEditor1);
            this.Controls.Add(this.tpsLabel1);
            this.Controls.SetChildIndex(this.tpsLabel1, 0);
            this.Controls.SetChildIndex(this.dataEditor1, 0);
            this.Controls.SetChildIndex(this.led1, 0);
            this.ResumeLayout(false);
        }
        #endregion
    }
}
